# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code_text', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('project_leader', models.CharField(max_length=200)),
                ('project_staffing', models.CharField(max_length=200)),
                ('project_status', models.CharField(max_length=200)),
                ('project_team', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
